version: "3.8"

services:
    database:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: P1234U
            MYSQL_DATABASE: bookstore_db
            MYSQL_USER: pauls
            MYSQL_PASSWORD: 123456789
        networks:
            - paulsnet
    myapp:
        build: .
        restart: always
        depends_on:
            - database
        ports:
            - "80:80"
        networks:
            - paulsnet

networks:
    paulsnet:
        driver: bridge